codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore:
    - "tests/*"
    - "src/mixins/*"


comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
