
blank_issues_enabled: false
contact_links:
  - name: 🤔 Have a Question?
    url: https://stackoverflow.com/questions/tagged/vue-chartjs/
    about: Feel free to ask questions on Stack Overflow.
  - name: 📊 Have a Problem With Chart.js?
    url: https://github.com/chartjs/Chart.js/issues
    about: vue-chartjs is just the wrapper around Chart.js, so if you are experiencing an issue with charts rendering, please create a related issue in Chart.js repository.
